#Screen
SIDEBAR_WIDTH = 250
SCREEN_WIDTH = 1280 + SIDEBAR_WIDTH
SCREEN_HEIGHT = 800
FPS = 60

#Board
ROWS = 8
COLS = 8
CELL_SIZE = 80
BOARD_SIZE = CELL_SIZE * ROWS

#Piece
PIECE_SIZE = int(CELL_SIZE * 0.7)
OFFSET = (CELL_SIZE - PIECE_SIZE) // 2

#Positioning
ORIGIN_X = (SCREEN_WIDTH - BOARD_SIZE) // 2
ORIGIN_Y = (SCREEN_HEIGHT - BOARD_SIZE) // 2

#Assets
ASSETS_PATH = "assets/"
IMAGE_PATH = ASSETS_PATH + "images/"
SOUND_PATH = ASSETS_PATH + "sounds/"
PIECES_PATH = IMAGE_PATH + "pieces/"
CELL_PATH = IMAGE_PATH + "board/"

#General
TITLE = "Chess Project X"
BG_COLOR = (40, 44, 52)
HIGHLIGHT_COLOR = (173, 216, 230)
COLOR_PANEL = (33, 33, 33)
COLOR_TEXT = (240, 240, 240)
LOG_PADDING_TOP = 60
LOG_PADDING_LEFT = 20
LOG_LINE_HEIGHT = 25